module DSD {
  module T1 {
    module Entity {
      interface Pessoa {
        attribute long id;
        attribute string cpf;
        attribute string nome;
        attribute string endereco;
        attribute long departamento;
      };

      interface Funcionario : Pessoa {
        attribute string ctps;
        attribute long quantidadeVendas;
      };

      interface Transportador : Pessoa {
        attribute string telefone;
        attribute long carregamento;
      };

      interface Departamento {
        string getNome();
        string getProduto();
        long getQuantidadeEstoque();
        void setProduto(in string produto);
        void setQuantidadeEstoque(in long quantidadeEstoque);
      };
    };
  };
};