module DSD {
  module T3 {
    module Entity {
      interface Departamento {
        string getNome();
        string getProduto();
        long getQuantidadeEstoque();
        void setProduto(in string produto);
        void setQuantidadeEstoque(in long quantidadeEstoque);
      };
    };
  };
};
